spring.application.name=formBuilder


server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/formbuilder
spring.datasource.username=postgres
spring.datasource.password=15072004
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.servlet.session.timeout=15m
app.upload.profile-photo-dir=./uploads/profile-photo
app.upload.form-files-dir=./uploads/form-files
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=100MB

# Form Builder Limits
app.limits.max-fields-per-form=50
app.limits.max-validations-per-form=100
app.limits.max-pages-per-form=10